capp/__init__.py
from flask import Flask
application = Flask(__name__)

from capp.home.routes import home
from capp.methodology.routes import methodology
from capp.carbon_app.routes import carbon_app
from capp.users.routes import users

application.register_blueprint(home)
application.register_blueprint(methodology)
application.register_blueprint(carbon_app)
application.register_blueprint(users)





capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint

carbon_app=Blueprint('carbon_app',__name__)

@carbon_app.route('/carbon_app')
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

@carbon_app.route('/carbon_app/new_entry')
def new_entry():
    return render_template('carbon_app/new_entry.html', title='new_entry')

@carbon_app.route('/carbon_app/your_data')
def your_data():
    return render_template('carbon_app/your_data.html', title='your_data')
    

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/methodology/__init__.py
#

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/__init__.py
#

capp/users/routes.py
from flask import render_template, Blueprint

users=Blueprint('users',__name__)

@users.route('/register')
def register():
  return render_template('users/register.html', title='register')

@users.route('/login')
def login():
  return render_template('users/login.html', title='login') 

capp/templates/carbon_app/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left;">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Methodology</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;", data-toggle="modal" data-target="#carbon_app_instructions">Instructions</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.new_entry')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">New entry</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.your_data')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Your data</a>
                </div>
            </div>  
            <!-- Modal Instructions -->
            <div class="modal fade" id="carbon_app_instructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
          
                    <div class="modal-header">
                    <h5 class="modal-title", style="color:black; text-align: center;">Carbon App, instructions</h5>
                    </div>
          
                    <div class="modal-body", style="color:black">
                    <p style="text-align: left;">
                    This tool allows you to estimate your carbon emissions based on 
                    transport activity. By entering distance travelled and fuel type, 
                    the system calculates the estimated CO₂ emissions using standardized emission factors.                    </p>
                    <ol style="text-align:left;">
                        <li>Introduce the number of kilometers.</li>
                        <li>Introduce the type of fuel</li>
                    </ol>
                    </div>
          
                    <div class="modal-footer">
                        <a href="{{url_for('carbon_app.new_entry')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">New entry</a>
                        <button class="btn btn-secondary btn-lg mr-2", style="background-color:#6c757d;" data-dismiss="modal">Close</button>
                    </div>
          
                </div>
                </div>
            </div>
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/calculator.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
        
        </div>
    </section> 
       

{% endblock content %}

capp/templates/carbon_app/new_entry.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_carbon_app">
    <div class="container">

        <div class="header_carbon_app">
            
            <div class="box"> 
                <h1 style="font-size:55px;">
                    <span class="text-logo">New Entry</span>
                </h1>
            </div>

            <div class="box">
                <img 
                    src="{{url_for('static', filename='icons/calculator.svg')}}"
                    width="325" 
                    height="325"
                    alt=""/>
            </div>

        </div>

    </div>
</section>

{% endblock content %}

capp/templates/carbon_app/your_data.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_carbon_app">
    <div class="container">

        <div class="header_carbon_app">
            
            <div class="box"> 
                <h1 style="font-size:55px;">
                    <span class="text-logo">Your Data</span>
                </h1>
            </div>

            <div class="box">
                <img 
                    src="{{url_for('static', filename='icons/calculator.svg')}}"
                    width="325" 
                    height="325"
                    alt=""/>
            </div>

        </div>

    </div>
</section>

{% endblock content %}

capp/templates/home.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_home">
  <div class="container">

    <div class="header_home">
      <div class="box"> 
        <h1 style="font-size:55px; font-family: 'Times New Roman', Times, serif;">
          <span class="text-logo">Home</span>
        </h1>

        <p style="text-align:left;">
          Welcome to Carbon App. We are a team of students in economics and technology, working together to explore how digital tools can support more sustainable decisions. Through our project, we combine academic knowledge with practical development to better understand climate impact, data analysis, and responsible innovation. Our goal is to transform complex environmental information into simple, accessible insights that help individuals and organizations take meaningful action. By bridging theory and practice, we aim to demonstrate how technology can contribute to a greener and more informed future.
        </p>

        <div class="container_buttons_links_header_home">
          <div class="btn">
            <a href="{{url_for('users.register')}}" class="btn btn-primary btn-lg mr-2" style="background-color:#007bff;">Register</a>
          </div>
          <div class="btn">
            <a href="{{url_for('users.login')}}" class="btn btn-primary btn-lg mr-2" style="background-color:#007bff;">Login</a>
          </div>
        </div>  
      </div>

      <div class="box">
        <img 
          src="{{url_for('static', filename='icons/carbon_app.svg')}}"
          width="325" 
          height="325"
          alt=""/>
      </div>
    </div>

  </div>
</section> 

<!-- Developers -->
<section class="section_developers">
  <div class="container">

    <div class="developers" style="display:block;">
      <h1 style="text-align:center; color:#568c63;"> Our Team</h1>
      <p style="color:#fff;">
        We are a team of economists and app developers passionate about turning data into smart, practical solutions. Together we design and build technology that helps people make better, more sustainable decisions.
      </p>      
    </div>

    <div class="developers">
      <div class="box">
        <img src="https://media.licdn.com/dms/image/v2/D4E03AQGEs456ZlnQlg/profile-displayphoto-scale_400_400/B4EZvN1ywzIwAg-/0/1768684990746?e=1772668800&v=beta&t=yisTf_dk9hbNXQXv_X7zhUZoCUBjF2Dn0P35TwNsaXU" alt="" style="border-radius: 50%; width:200px;">
        <h3>Elias Kyte</h3>
        <p>
          Elias Kyte was born in 2005 and is originally from Bergen, Norway. He is currently studying at the Norwegian School of Economics (NHH). Prior to beginning his studies, he completed his military service. With his background from both the armed forces and a leading business school, Elias represents a combination of discipline, dedication, and academic ambition.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="https://www.linkedin.com/in/elias-kyte-612b91268/" target="_blank">Linkedin</a>
        </div> 
      </div>

      <div class="box">
        <img src="https://media.licdn.com/dms/image/v2/D4D03AQEXE_lwqsLMAg/profile-displayphoto-scale_400_400/B4DZonDX6NKIAg-/0/1761591787920?e=1772668800&v=beta&t=KKKjh1dd6hceIe0D1fQw3xxRfB6XWAPZWu6IXNK6Fsw" alt="" style="border-radius: 50%; width:200px;">
        <h3>Trond Heløe</h3>
        <p>
          Trond Heløe was born in 2004 and is currently studying at the Norwegian School of Economics (NHH). Before starting his academic journey, he completed his military service, gaining valuable experience and discipline. Through his background in both the armed forces and business education, Trond demonstrates commitment, responsibility, and strong academic motivation.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="https://www.linkedin.com/in/trond-heidenreich-hel%C3%B8e-604a61255/" target="_blank">Linkedin</a>
        </div> 
      </div>           

      <div class="box">
        <img src="https://randomuser.me/api/portraits/men/12.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Filip Odgaard Dimcevski</h3>
        <p>
          Filip was born in 2005 and is originally from Bergen, Norway. He is currently studying at the Norwegian School of Economics (NHH). As a student at one of Norway’s leading business schools, Filip is building a strong academic foundation while developing skills in economics and business.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="https://www.fotball.no/fotballdata/kamp/?fiksId=8817616" target="_blank">Linkedin</a>
        </div> 
      </div>     
    </div>

    <div class="developers">
      <div class="box2">
        <img src="https://randomuser.me/api/portraits/men/12.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Sarah Hess</h3>
        <p>
          We are a team of economists and app developers passionate about turning data into smart, practical solutions. Together we design and build technology that helps people make better, more sustainable decisions.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="https://www.linkedin.com/in/sarah-he%C3%9F-613b37297/" target="_blank">Linkedin</a>
        </div> 
      </div>

      <div class="box2">
        <img src="https://media.licdn.com/dms/image/v2/D5603AQHK67KR8t5T_g/profile-displayphoto-shrink_400_400/B56ZeERW69GoAo-/0/1750270833407?e=1772668800&v=beta&t=ktIpf_HH4DdHTkwIcvux0rLFSzAeI8hEd8rBbG-YOOQ" alt="" style="border-radius: 50%; width:200px;">
        <h3>Victor Rande</h3>
        <p>
          We are a team of economists and app developers passionate about turning data into smart, practical solutions. Together we design and build technology that helps people make better, more sustainable decisions.
        </p>
        <div class="section_container_buttons_developers">
          <a class="btn_developers" href="https://www.linkedin.com/in/victor-rande-7708ab358/" target="_blank">Linkedin</a>
        </div> 
      </div>           

      
      <div class="box2">  
       <img src="https://randomuser.me/api/portraits/men/32.jpg" alt="Loic" style="border-radius: 50%; width:200px;">
       <h3>Loic</h3>
       <p>
        Loic is passionate about building efficient, scalable solutions and turning complex ideas into clean, user-friendly applications. With a strong interest in technology and innovation, he focuses on creating tools that make a real-world impact.
       </p>
       <div class="section_container_buttons_developers">
       <a class="btn_developers" href="LINKEDIN_URL_HER" target="_blank">Linkedin</a>
       </div>   
    </div>

  </div>          
</section>
        
{% endblock content %}



capp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Font Awesome code -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Import the Bootstrap CSS file: -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />

    <!-- MathJax -->
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

    <!-- CSS code -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">

    <!-- To activate media queries in devices -->
    <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>home</title>
    {% endif %}
  </head>

  <body>
    <section class="section_carbon_app_navbar">
      <div class="container">
        <div class="carbon_app_navbar">
          <h1 class="logo">
            <!-- OLD formatting kept: globe icon -->
            <span class="text-logo"><i class="fa-solid fa-globe"></i> Carbon</span> App
          </h1>

          <nav>
            <ul>
              <!-- NEW functionality kept -->
              <li><a href="{{ url_for('home.home_home') }}">Home</a></li>
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
              <li><a href="{{ url_for('users.login') }}">Login</a></li>
              <li><a href="{{ url_for('methodology.methodology_home') }}">Methodology</a></li>
              <li><a href="{{ url_for('carbon_app.carbon_app_home') }}">Carbon App</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </section>

    {% block content %}{% endblock %}

    <section class="section_footer">
      <div class="container">
        <div class="footer">
          <h1>
            Carbon App
            <a href="#">
              <i class="fa-solid fa-circle-up" style="color: #568c63"></i>
            </a>
          </h1>
        </div>
      </div>
    </section>

    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>

    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

capp/templates/methodology.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_methodology">
  <div class="container">

    <div class="header">
      <div class="box"> 
        <h1 style="font-size:55px; font-family: 'Times New Roman', Times, serif;">
          <span class="text-logo"> Methodology</span>
        </h1>

        <p style="text-align:left;">
          Our website allows users to calculate their own carbon emissions by entering information about their daily activities, such as transportation, energy use, and consumption habits.
          <br><br>
          Based on the data you provide, we apply standard emission factors (for example, CO₂ per kilometer driven or per kWh of electricity used) to estimate your total carbon footprint. The system multiplies your input by these emission factors and then adds everything together to give you an overall estimate of your carbon emissions.
          <br><br>
          This method provides a simple and personalized way to understand your environmental impact.
        </p>

        <div class="container_buttons_links_header">
          <div class="btn">
            <a href="#" class="btn btn-primary btn-lg mr-2" style="background-color:#007bff;">Paper</a>
          </div>
          <div class="btn">
            <a href="{{url_for('carbon_app.carbon_app_home')}}" class="btn btn-primary btn-lg mr-2" style="background-color:#007bff;">Carbon App</a>
          </div>
        </div>  
      </div>

      <div class="box">
        <img 
          src="{{url_for('static', filename='icons/methodology2.svg')}}"
          width="325" 
          height="325"
          alt=""/>
      </div>
    </div>
    
  </div>
</section> 

<!-- Methodology -->
<section class="section_body_methodology">
  <div class="container">

    <div class="methodology" style="display:block;">
      <h1 style="text-align:center;"> Methodology</h1>
      <p>
        The following mathematical expressions represent the analytical foundation of our application. They describe the relationships between key variables used in our calculations and illustrate how theoretical models are translated into practical algorithms within the system.
      </p>      
    </div>

    <div class="methodology" style="display:block;">
      <h1 style="text-align:center;"> Our numbers and formulas</h1>
      <p>
        Attached are the \(\LaTeX ~ formulas\) that will form the core of our profject:
      </p> 
    </div>

    <!--Enumerated list (table with two columns)-->
    <div class="methodology"> 
      <div class="box_table2" style="height:200px;">
        <ol start="1">
          <li>
            <h4>Mathematical expressions 1</h4>
            <p class="text-left">
              Mathematical expressions \( x = {-b \pm \sqrt{b^2-4ac} \over 2a} \) inside text.
              <br>
              Mathematical expressions outside text:
              \[ x = {-b \pm \sqrt{b^2-4ac} \over 2a} \]
            </p>
          </li>
        </ol>                        
      </div>

      <div class="box_table2" style="height:200px;">
        <ol start="2">
          <li>
            <h4>Mathematical expressions 2</h4>
            <p class="text-left">
              Mathematical expressions \( x^2 + y^2 = z^2 \) inside text.
              <br>
              Mathematical expressions outside text:
              \[ x^2 + y^2 = z^2 \]
            </p>
          </li>
        </ol>
      </div>  
    </div>

    <!--Enumerated list (table with two columns)-->
    <div class="methodology"> 
      <div class="box_table2" style="height:425px;">
        <ol start="3">
          <li>
            <h4>Sums</h4>
            <p class="text-left">
              Sum \(\sum_{n=1}^{\infty} 2^{-n} = 1\) inside text.
              <br>
              Sum outside text:
              \[ \sum_{n=1}^{\infty} 2^{-n} = 1 \]
            </p>
          </li>
          <li>
            <h4>Products</h4>
            <p class="text-left">
              Product \(\prod_{i=a}^{b} f(i)\) inside text.
              <br>
              Product outside text:
              \[ \prod_{i=a}^{b} f(i) \]
            </p>
          </li>
        </ol>                        
      </div>

      <div class="box_table2" style="height:425px;">
        <ol start="5">
          <li>
            <h4>Limits</h4>
            <p class="text-left">
              Limit \(\lim_{x\to\infty} f(x)\) inside text.
              <br>
              Limit outside text:
              \[ \lim_{x\to\infty} f(x) \]
            </p>
          </li>
          <li>
            <h4>Integrals</h4>
            <p class="text-left">
              Integral \(\int_{a}^{b} x^2 \,dx\) inside text.
              <br>
              Integral outside text:
              \[ \int_{a}^{b} x^2 \,dx \]
            </p>
          </li>
        </ol>
      </div>  
    </div>

    <!--Enumerated list (table with one column)-->
    <div class="methodology">              
      <div class="box_table1"></div>

      <div class="box_table1">
        <ol>
          <li>
            <h4>Buses</h4>
            <p class="text-left">
              The <strong>carbon dioxide emissions</strong> produced by buses are organized in <strong>four categories</strong>. The carbon dioxide emission produced by diesel buses is 0.10231 grammes per kilometer. The carbon dioxide emission produced by CNG buses is 0.08 grammes per kilometer. The carbon dioxide emission produced by petrol buses is 0.10231 grammes per kilometer. If the buses do not use fossil fuel, their dioxide carbon emissions are 0 grammes per kilometer.
              <br>
              To work out buses dioxide emissions, we use the next formula:
              \[CO^2 = {Cte + \sqrt{f(km)} \over t}.\]
              <br>
              Where:
              <ul style="text-align:left;">
                <li>\(Cte\) is a constant, since the engine requires some fuel to initialize.</li>
                <li>\(km\) are the kilometers.</li>
                <li>\(f\) is a coefficient depending on the type of fuel (see paragraph above).</li>
                <li>\(t\) is the temperature, since in winter the engines require less fuel.</li>
              </ul>
            </p>
          </li>
          <li>
            <h4>Cars</h4>
            <p class="text-left">...</p>
          </li>
          <li>
            <h4>Planes</h4>
            <p class="text-left">...</p>
          </li>
        </ol>                        
      </div>

      <div class="box_table1"></div>  
    </div>

  </div>
</section>

{% endblock content %}



capp/templates/users/login.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_carbon_app">
    <div class="container">

        <div class="header_carbon_app">
            
            <div class="box"> 
                <h1 style="font-size:55px;">
                    <span class="text-logo">Login Here</span>
                </h1>
                <div class="login-box">
                    <form method="POST">
                        <input class="login-input" type="text" name="username" placeholder="Username" required>
                        <input class="login-input" type="password" name="password" placeholder="Password" required>
                        <button class="login-btn" type="submit">Login</button>
                    </form>
                </div>
            </div>

            <div class="box">
                <img 
                    src="{{url_for('static', filename='icons/arrow_left.svg')}}"
                    width="325" 
                    height="325"
                    alt=""/>
            </div>

        </div>

    </div>
</section>

{% endblock content %}

capp/templates/users/register.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_carbon_app">
    <div class="container">

        <div class="header_carbon_app">
            
            <div class="box"> 
                <h1 style="font-size:55px;">
                    <span class="text-logo">Register Here</span>
                </h1>
                
                <!-- REGISTER FORM -->
                <div class="login-box" onsubmit="showMessage()">
                    <form method="POST">
                        <input class="login-input" type="text" name="first_name" placeholder="First name" required>
                        <input class="login-input" type="email" name="email" placeholder="Email" required>
                        <input class="login-input" type="password" name="password" placeholder="Password" required>
                        <button class="login-btn" type="submit">Register</button>
                    </form>
                </div>
            </div>

            <div class="box">
                <img 
                    src="{{url_for('static', filename='icons/register.svg')}}"
                    width="325" 
                    height="325"
                    alt=""/>
            </div>

        </div>

    </div>


</section>

<script>
function showMessage() {
    alert("🎉 Registration successful!");
}
</script>


    

{% endblock content %}